//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRoom
    {
        public int ClassRoomID { get; set; }
        public int CourseID { get; set; }
        public int BuildingID { get; set; }
        public int RoomID { get; set; }
        public System.TimeSpan StartTime { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Course Course { get; set; }
        public virtual Room Room { get; set; }
    }
}
