//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CourseLocations
    {
        public string Title { get; set; }
        public string BuildingName { get; set; }
        public int RoomNum { get; set; }
        public int Capacity { get; set; }
        public System.TimeSpan StartTime { get; set; }
    }
}
